name: Deploy Web3 plugin files

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 📥 Check out the code...
        uses: actions/checkout@v3

      - name: ⚒️ Set up Node.js v${{ matrix.node-version }}...
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⚙️ Installing dependencies...
        run: npm install

      - name: 🚀 Building application...
        run: npm run build

      - name: 🖥️ Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
        run: |
          aws s3 cp dist/plugin.js s3://cdn.earnm.com/static/plugin.js --acl public-read --content-type "application/javascript"
          aws s3 cp dist/plugin.css s3://cdn.earnm.com/static/plugin.css --acl public-read --content-type "text/css"
